# Generated by Django 2.0 on 2019-01-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='importance',
            field=models.FloatField(choices=[(0, 'None'), (1, 'Not relevant'), (2, 'Review'), (3, 'May relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=0),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='unlockquestion',
            field=models.ManyToManyField(blank=True, null=True, related_name='unlockquestion', to='voting.Question'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='isWeighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voting',
            name='questions',
            field=models.ManyToManyField(related_name='voting', to='voting.Question'),
        ),
    ]
