# Generated by Django 2.0 on 2018-11-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
    ]
