# Generated by Django 2.0 on 2019-01-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20190109_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='unlockquestion',
            field=models.ManyToManyField(blank=True, related_name='unlockquestion', to='voting.Question'),
        ),
    ]
