# Generated by Django 2.0 on 2018-11-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20181125_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(),
        ),
    ]
