# Generated by Django 2.0 on 2018-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20181207_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='votings',
            field=models.ManyToManyField(related_name='questions', to='voting.Voting'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
