# Generated by Django 2.0 on 2018-11-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20181126_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeropenquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voting',
        ),
        migrations.AddField(
            model_name='voting',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.Question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnswerOpenQuestion',
        ),
        migrations.DeleteModel(
            name='OpenQuestion',
        ),
    ]
