# Generated by Django 2.0 on 2018-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20181126_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='referendum',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
