# Generated by Django 2.0 on 2018-11-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_question_referendum'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='isWeighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='referendum',
            field=models.BooleanField(default=False),
        ),
    ]
