# Generated by Django 2.0 on 2018-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20181127_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='questions',
            field=models.ManyToManyField(related_name='voting', to='voting.Question'),
        ),
    ]
