# Generated by Django 2.0 on 2019-01-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180921_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
