# Generated by Django 2.0 on 2019-01-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180921_1119'),
        ('mixnet', '0004_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Auth')),
            ],
        ),
    ]
