# Generated by Django 2.1.5 on 2019-01-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixnet', '0005_connectionstatus'),
        ('mixnet', '0005_auto_20190113_1203'),
    ]

    operations = [
    ]
