# Generated by Django 2.0 on 2018-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180921_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='question_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
